name: Daily Ruoff Scrape

on:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 6:00 AM EST (11:00 UTC during standard time)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
          echo "--- Verifying credentials.json content ---"
          cat credentials.json
          echo "----------------------------------------"
          echo "${{ secrets.GOOGLE_TOKEN_JSON }}" > token.json
        shell: bash

      - name: Run scrape script
        run: python scrape_ruoff_shows.py

      - name: Commit and push updated files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ruoff_shows.csv ruoff_shows.html last_known_shows.txt docs/index.html
          git commit -m "Automated daily scrape: $(date -u)" || echo "No changes to commit"
          echo "GH_PAT is ${GH_PAT:0:5}... (length: ${#GH_PAT})"
          git push https://x-access-token:${GH_PAT}@github.com/jcorio/RuoffToCal.git HEAD:master
