name: Scrape Ruoff Shows

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create service account file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' | jq '.' > service-account.json
          
      - name: Run scraper
        run: python scrape_ruoff_shows.py

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit and push if changed
        run: |
          git add ruoff_shows.html ruoff_shows.csv last_known_shows.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped shows data" && git push) 